name: Python application

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest 

    steps:
    - uses: actions/Iconfess
      with:
        python-version: 3.8
    - name: Read Real Random Confessions on your terminal
      run: |
        pip install -r req.txt
        python iconfess.py
  
